### ISSUE TITLE
Sonarr-sma "Check for Finished Download" task stuck when PostSonarr is running

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#1022]
I'm using your Sonarr-sma docker container and have an issue with it when the PostSonarr script is converting a certain media file that's take around 1 hour or so. Here's more details about it:

https://forums.sonarr.tv/t/check-for-finished-download-task-stuck-when-file-is-post-processing/22576

markus101 has a good point that the script should fork to a new process so that Sonarr will continue updating the other downloads while ffmpeg is trying to convert a certain media file. Is this something that you can fix?

**Comment by kevindd992002** [comment]
@mdhiggins, just wanted to follow-up on this concern? Thanks.

**Comment by mdhiggins** [comment]
I just pushed an update that fixed a bug where that could hang for a very long time, try the latest update (had to do with failed artwork download not having a timeout, would sit indefinitely)

**Comment by kevindd992002** [comment]
Thanks, let me monitor and see if this happens again.

**Comment by kevindd992002** [comment]
@mdhiggins This issue is still happening. Sonarr doesn't update in realtime because the custom script (sma) it runs is processing media files for a long time. This is one of the main reason why it's really better to do the post-processing in the download clients (nzbget, deluge, etc.) instead of doing it in the media managers.

Is there any way you can consider maintaining docker containers for download clients with sma instead? I really think this would fix a lot of issues similar to this one.

**Comment by kevindd992002** [comment]
@mdhiggins , any other ideas to fix this issue?

**Comment by kevindd992002** [comment]
@mdhiggins , I was wondering if you could still help me with this? I'm at a loss here.
