### ISSUE TITLE
Error when attempting to burn-in subtitles using vaapi

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1183]
I'm still looking online for a solution, but I think the error is caused because the same method for non-accelerated burn-in does not work for HW accelerated burn in.

Not using vaapi, does work normally.

Here is ffmpeg's page with information: https://trac.ffmpeg.org/wiki/Hardware/VAAPI

ffmpeg's example: 
```
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i input.mp4 -vf 'scale_vaapi,hwmap=mode=read+write+direct,format=nv12,ass=subtitles.ass,hwmap' -c:v h264_vaapi -b:v 2M -maxrate 2M output.mp4
```

Here is the output from the command trying to run via the script:

```
/usr/local/bin/ffmpeg -fix_sub_duration -i "/storage/media/tv/show/Season/episdoe.mkv" -vcodec h264_vaapi -map 0:0 -field_order progressive -vb 6000k -level 4.0 -vaapi_device /dev/dri/renderD128 -vf subtitles='/storage/media/tv/show/Season/episdoe.mkv':si=0;format=nv12,hwupload -c:a:0 copy -map 0:2 -metadata:s:a:0 title=5.1 Channel -metadata:s:a:0 language=eng -disposition:a:0 +default -c:s:0 mov_text -map 0:3 -disposition:s:0 +default -metadata:s:s:0 language=eng -c:s:1 mov_text -map 0:4 -metadata:s:s:1 language=eng -c:s:2 mov_text -map 0:5 -metadata:s:s:2 language=eng -f mp4 -threads 0 -metadata:g encoding_tool=SMA -level 40 -maxrate 6000k -y "/storage/media/tv/show/Season/episdoe.mp4"
```

The error message:

```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
  Stream #0:2 -> #0:1 (copy)
  Stream #0:3 -> #0:2 (subrip (srt) -> mov_text (native))
  Stream #0:4 -> #0:3 (subrip (srt) -> mov_text (native))
  Stream #0:5 -> #0:4 (subrip (srt) -> mov_text (native))
Press [q] to stop, [?] for help
[Parsed_subtitles_0 @ 0x55b454d1e600] Shaper: FriBidi 0.19.7 (SIMPLE)
Fontconfig error: Cannot load default config file
[Parsed_subtitles_0 @ 0x55b454d1e600] No usable fontconfig configuration file found, using fallback.
Fontconfig error: Cannot load default config file
[Parsed_subtitles_0 @ 0x55b454d1e600] Using font provider fontconfig
Simple filtergraph 'subtitles='/storage/media/tv/show/Season/episdoe.mkv':si=0;format=nv12,hwupload' was expected to have exactly 1 input and 1 output. However, it had >1 input(s) and >1 output(s). Please adjust, or use a complex filtergraph (-filter_complex) instead.
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!
```

**Comment by mdhiggins** [comment]
Does changing to `subtitles='/storage/media/tv/show/Season/episdoe.mkv':si=0,format=nv12,hwupload` make any difference?

**Comment by RandomNinjaAtk** [comment]
That is what the existing command uses

**Comment by mdhiggins** [comment]
No I switched a comma and semicolon

**Comment by RandomNinjaAtk** [comment]
Running the command manually and changing that did change the error message:

```
/usr/local/sma# ffmpeg -fix_sub_duration -i "/storage/media/tv/file.mkv" -vcodec h264_vaapi -map 0:0 -field_order progressive -vb 6000k -level 4.0 -vaapi_device /dev/dri/renderD128 -vf subtitles='/storage/media/tv/file.mkv':si=0,format=nv12,hwupload -c:a:0 copy -map 0:2 -metadata:s:a:0 title=5.1 Channel -metadata:s:a:0 language=eng -disposition:a:0 +default -c:s:0 mov_text -map 0:3 -disposition:s:0 +default -metadata:s:s:0 language=eng -c:s:1 mov_text -map 0:4 -metadata:s:s:1 language=eng -c:s:2 mov_text -map 0:5 -metadata:s:s:2 language=eng -f mp4 -threads 0 -metadata:g encoding_tool=SMA -level 40 -maxrate 6000k -y "/storage/media/tv/file.mp4"
ffmpeg version N-96918-gd99f3dc Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 42.100 / 56. 42.100
  libavcodec     58. 74.100 / 58. 74.100
  libavformat    58. 40.100 / 58. 40.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Guessed Channel Layout for Input Stream #0.1 : 5.1
Guessed Channel Layout for Input Stream #0.2 : 5.1
Input #0, matroska,webm, from '/storage/media/tv/file.mkv':
  Metadata:
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-02-25T17:19:53.000000Z
  Duration: 00:45:41.41, start: 0.000000, bitrate: 10268 kb/s
    Stream #0:0: Video: h264, yuv420p(tv, bt709/unknown/unknown, progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS-eng         : 8987352
      DURATION-eng    : 00:45:40.988000000
      NUMBER_OF_FRAMES-eng: 65718
      NUMBER_OF_BYTES-eng: 3079278316
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(fre): Audio: eac3, 48000 Hz, 5.1, fltp (default)
    Metadata:
      title           : French
      BPS-eng         : 640000
      DURATION-eng    : 00:45:41.408000000
      NUMBER_OF_FRAMES-eng: 85669
      NUMBER_OF_BYTES-eng: 219312640
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: eac3, 48000 Hz, 5.1, fltp
    Metadata:
      title           : English
      BPS-eng         : 640000
      DURATION-eng    : 00:45:41.408000000
      NUMBER_OF_FRAMES-eng: 85669
      NUMBER_OF_BYTES-eng: 219312640
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(fre): Subtitle: subrip (default) (forced)
    Metadata:
      title           : French (Forced)
      BPS-eng         : 2
      DURATION-eng    : 00:41:33.950000000
      NUMBER_OF_FRAMES-eng: 33
      NUMBER_OF_BYTES-eng: 719
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(fre): Subtitle: subrip
    Metadata:
      title           : French
      BPS-eng         : 41
      DURATION-eng    : 00:45:13.586000000
      NUMBER_OF_FRAMES-eng: 538
      NUMBER_OF_BYTES-eng: 14026
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS-eng         : 55
      DURATION-eng    : 00:44:36.924000000
      NUMBER_OF_FRAMES-eng: 643
      NUMBER_OF_BYTES-eng: 18600
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[NULL @ 0x564e9c30b0c0] Unable to find a suitable output format for 'Channel'
Channel: Invalid argument
```

**Comment by mdhiggins** [comment]
Looks like something you changed is actually just breaking the command due to lack of quotes somewhere

Rather than deal with that, if you open ./converter/avcodecs.py and change line 424 you can change that character in the code

`                vfstring = "%s;%s" % (vfstring, line)`
to
`                vfstring = "%s,%s" % (vfstring, line)`

**Comment by RandomNinjaAtk** [comment]
Okay, edited and I think its working ;)

**Comment by mdhiggins** [comment]
Nice, keep me posted. That would be an easy fix and I'll update if it works

**Comment by RandomNinjaAtk** [comment]
The fact that it did not error immediately and it is encoding. It's safe to say it's fixed.

**Comment by mdhiggins** [comment]
Make sure the burned subs actually appear 😝

**Comment by mdhiggins** [comment]
d48332244433f1bbea69ab13e80d3cf25db9323e

**Comment by RandomNinjaAtk** [comment]
Yes looks like it worked.

**Comment by RandomNinjaAtk** [comment]
One side issue I see with this, is it seems the forced burn-in / flag doesn't also account for set language. So in my case id want only forced subs in English. This burned in the sub but it's in French because that's the one that was tagged. A small change should probably be added to be able to account for that.

**Comment by mdhiggins** [comment]
Hm that's an oversight. It is applied for external subtitles but not for embedded
bc5322f6d1ed068ca3de9595793af9439d533a07
Should fix it

**Comment by RandomNinjaAtk** [comment]
Nice, still seeing a possible issue, maybe should open a seperate thread, because this is technially fixed. But it seems the script is relableling subtitles languages or not respecting them,

See image:
![image](https://user-images.githubusercontent.com/8386416/76707932-7d9b2280-66c9-11ea-8ef3-85165501ebf8.png)

Sub config settings:
```
[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
encoding = 
burn-subtitles = forced
download-subs = False
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
attachment-codec = 
first-stream-of-language = False
ignore-embedded-subs = False
```

**Comment by mdhiggins** [comment]
Could you post the ffprobe -show_streams data for that file

**Comment by RandomNinjaAtk** [comment]
ffprobe
```
Input #0, matroska,webm, from '/storage/media/tv/file.mkv':
  Metadata:
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-02-25T17:19:53.000000Z
  Duration: 00:45:41.41, start: 0.000000, bitrate: 10268 kb/s
    Stream #0:0: Video: h264, yuv420p(tv, bt709/unknown/unknown, progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS-eng         : 8987352
      DURATION-eng    : 00:45:40.988000000
      NUMBER_OF_FRAMES-eng: 65718
      NUMBER_OF_BYTES-eng: 3079278316
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(fre): Audio: eac3, 48000 Hz, 6 channels, fltp (default)
    Metadata:
      title           : French
      BPS-eng         : 640000
      DURATION-eng    : 00:45:41.408000000
      NUMBER_OF_FRAMES-eng: 85669
      NUMBER_OF_BYTES-eng: 219312640
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: eac3, 48000 Hz, 6 channels, fltp
    Metadata:
      title           : English
      BPS-eng         : 640000
      DURATION-eng    : 00:45:41.408000000
      NUMBER_OF_FRAMES-eng: 85669
      NUMBER_OF_BYTES-eng: 219312640
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(fre): Subtitle: subrip (default) (forced)
    Metadata:
      title           : French (Forced)
      BPS-eng         : 2
      DURATION-eng    : 00:41:33.950000000
      NUMBER_OF_FRAMES-eng: 33
      NUMBER_OF_BYTES-eng: 719
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(fre): Subtitle: subrip
    Metadata:
      title           : French
      BPS-eng         : 41
      DURATION-eng    : 00:45:13.586000000
      NUMBER_OF_FRAMES-eng: 538
      NUMBER_OF_BYTES-eng: 14026
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS-eng         : 55
      DURATION-eng    : 00:44:36.924000000
      NUMBER_OF_FRAMES-eng: 643
      NUMBER_OF_BYTES-eng: 18600
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-25 17:19:53
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**Comment by mdhiggins** [comment]
Found the problem, single character typo
5120b16de9c7899d165cd47db18d54dc766de49b

**Comment by RandomNinjaAtk** [comment]
This seems to be resolved! Thanks!
