### ISSUE TITLE
Bug? Marking all audio streams as default?

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1202]
The log file does not show that its marking all audio streams as default, but when reviewing the files via mediainfo  or mpc, the properties shows all audio tracks as being default.

This happens will all streams, if UA + Converted + Copy is enabled, all 3 will be marked as default. The order will be correct based on the config, but marking is not, see example below:

Config settings:

```
[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
output-directory =
output-format = mkv
output-extension = mkv
temp-extension =
ignored-extensions = nfo, ds_store
copy-to =
move-to =
delete-original = True
sort-streams = True
process-same-extensions = True
force-convert = True
post-process = False
preopts =
postopts = -level,41,-maxrate,12000k

[Permissions]
chmod = 0666
uid = -1
gid = -1

[Metadata]
relocate-moov = False
full-path-guess = True
tag = False
tag-language = eng
download-artwork = poster
preserve-source-disposition = False

[Video]
codec = h264vaapi, h264, x264, h265, x265, hevc
bitrate = 0
crf = -1
crf-profiles =
max-width = 0
profile =
max-level = 0.0
pix-f

[Audio]
codec = eac3, ac3, opus, aac, mp3
languages = eng
default-language = eng
first-stream-of-language = True
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter =
sample-rates =
copy-original = True
aac-adtstoasc = False
ignore-truehd = mp4, m4v

[Universal Audio]
codec =
channel-bitrate = 64
first-stream-only = True
move-after = True
filter =

```

Example log output:
```
2020-03-26 19:37:27 - MANUAL - INFO - {
    "source": [
        "/storage/downloads/sabnzbd/complete/sonarr/file.mkv"
    ],
    "format": "mkv",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 8821.883349999998,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "debug": "video"
    },
    "audio": [
        {
            "map": 1,
            "codec": "eac3",
            "channels": 6,
            "bitrate": 768,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        },
        {
            "map": 1,
            "codec": "copy",
            "channels": 6,
            "language": "eng",
            "disposition": null,
            "title": "5.1 Channel",
            "debug": "audio-copy-original"
        }
    ],
    "subtitle": [
        {
            "map": 2,
            "codec": "srt",
            "language": "eng",
            "encoding": "",
            "disposition": "+default",
            "debug": "subtitle.embed-subs"
        },
        {
            "map": 3,
            "codec": "srt",
            "language": "eng",
            "encoding": "",
            "disposition": null,
            "debug": "subtitle.embed-subs"
        }
    ],
    "attachment": []
}
```

Result
```
General
Unique ID                      : 335938798392151870539166388751784042400 (0xFCBB7589936C40BA58FDF298E7015FA0)
Complete name                  : Z:\storage\media\tv\file.mkv
Format                         : Matroska
Format version                 : Version 4 / Version 2
File size                      : 3.47 GiB
Duration                       : 43 min 20 s
Overall bit rate               : 11.5 Mb/s
Writing application            : SMA
Writing library                : Lavf58.40.100
ErrorDetectionType             : Per level 1

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings, CABAC         : Yes
Format settings, RefFrames     : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Bit rate                       : 9 311 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Variable
Original frame rate            : 23.976 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.187
Writing library                : x264 core 148 r2705 3f5ed56
Encoding settings              : cabac=1 / ref=4 / deblock=1:-3:-3 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=1 / bitrate=9311 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=3:0.80
Default                        : Yes
Forced                         : No
Statistics Tags Issue          : no_variable_data 1970-01-01 00:00:00 / SMA 
FromStats_BitRate              : 9310504
FromStats_Duration             : 00:43:20.769000000
FromStats_FrameCount           : 62356
FromStats_StreamSize           : 3026804327

Audio #1
ID                             : 2
Format                         : E-AC-3
Format/Info                    : Enhanced Audio Coding 3
Format settings, Endianness    : Big
Codec ID                       : A_EAC3
Duration                       : 43 min 20 s
Bit rate mode                  : Constant
Bit rate                       : 640 kb/s
Channel(s)                     : 6 channels
Channel positions              : Front: L C R, Side: L R, LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 187.500 FPS (256 SPF)
Bit depth                      : 32 bits
Compression mode               : Lossy
Stream size                    : 198 MiB (6%)
Title                          : 5.1 Channel
Writing library                : Lavc58.74.100 eac3
Language                       : English
Service kind                   : Complete Main
Default                        : Yes
Forced                         : No
Statistics Tags Issue          : no_variable_data 1970-01-01 00:00:00 / SMA 
FromStats_BitRate              : 640000
FromStats_Duration             : 00:43:20.768000000
FromStats_FrameCount           : 243822
FromStats_StreamSize           : 490569864

Audio #2
ID                             : 3
Format                         : DTS
Format/Info                    : Digital Theater Systems
Mode                           : 16
Format settings, Endianness    : Big
Codec ID                       : A_DTS
Duration                       : 43 min 20 s
Bit rate mode                  : Constant
Bit rate                       : 1 509 kb/s
Channel(s)                     : 6 channels
Channel positions              : Front: L C R, Side: L R, LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 24 bits
Compression mode               : Lossy
Delay relative to video        : 5 ms
Stream size                    : 468 MiB (13%)
Title                          : 5.1 Channel
Language                       : English
Default                        : Yes
Forced                         : No
Statistics Tags Issue          : no_variable_data 1970-01-01 00:00:00 / SMA 
FromStats_BitRate              : 1509000
FromStats_Duration             : 00:43:20.772000000
FromStats_FrameCount           : 243822
FromStats_StreamSize           : 490569864

Text #1
ID                             : 4
Format                         : UTF-8
Codec ID                       : S_TEXT/UTF8
Codec ID/Info                  : UTF-8 Plain Text
Writing library                : Lavc58.74.100 srt
Language                       : English
Default                        : Yes
Forced                         : No
Statistics Tags Issue          : no_variable_data 1970-01-01 00:00:00 / SMA 
FromStats_BitRate              : 51
FromStats_Duration             : 00:41:43.507000000
FromStats_FrameCount           : 509
FromStats_StreamSize           : 16859

Text #2
ID                             : 5
Format                         : UTF-8
Codec ID                       : S_TEXT/UTF8
Codec ID/Info                  : UTF-8 Plain Text
Title                          : SDH
Writing library                : Lavc58.74.100 srt
Language                       : English
Default                        : No
Forced                         : No
Statistics Tags Issue          : no_variable_data 1970-01-01 00:00:00 / SMA 
FromStats_BitRate              : 54
FromStats_Duration             : 00:42:38.604000000
FromStats_FrameCount           : 553
FromStats_StreamSize           : 17835

Menu
00:00:00.000                   : :00:00:00.000
00:00:49.675                   : :00:00:49.675
00:11:30.857                   : :00:11:30.857
00:18:49.754                   : :00:18:49.754
00:24:27.383                   : :00:24:27.383
00:30:45.552                   : :00:30:45.552
00:34:53.174                   : :00:34:53.174
00:42:42.268                   : :00:42:42.268
```

**Comment by mdhiggins** [comment]
6f9c7be34a125729e85815abe80ffd828c49e2c0

Should be fixed, looks like FFMPEG copying disposition from source if its not explicitly set to negative

**Comment by RandomNinjaAtk** [comment]
@mdhiggins Looks like this partially fixed it?

When I have all 3 enabled, the copy-original still seems to be tagged as default.
