### ISSUE TITLE
Postprocessing fails to execute if tagging fails

### ISSUE THREAD

**Issue by bbobrian** [mdhiggins/sickbeard_mp4_automator#1289]
If tagging fails (season not found in tmdb), then postprocessing will fail:
 
2020-07-27 17:40:31 - resources.mediaprocessor - ERROR - Error processing
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 72, in fullprocess
    postprocessor.setEnv(mediatype, tag.tmdbid, season, episode)
UnboundLocalError: local variable 'tag' referenced before assignment

**Comment by mdhiggins** [comment]
4125cfd14349f8fa05199d6d4769ea40b877b8c9
That should fix it, good catch

**Comment by bbobrian** [comment]
It actually didn't fix:

2020-07-30 18:31:05 - resources.mediaprocessor - ERROR - Error processing
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 73, in fullprocess
    postprocessor.setEnv(mediatype, tmdbid, season, episode)
UnboundLocalError: local variable 'tmdbid' referenced before assignment

**Comment by mdhiggins** [comment]
4c6c389d5ae772d0c62596ee0741e501d1b65f32

Looks like there was a typo earlier in the script I didn't see (tmbdid instead of tmdbid), try now
