### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1438]
pythonpath=/usr/local/sma **/ven/** bin/python3
Should be `pythonpath=/usr/local/sma/venv/bin/python3`
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/qBittorrent-Unrar-Script

**Comment by mdhiggins** [comment]
Fixed, thanks

**Comment by morganzero** [comment]
Is this accurate in the script? Or should I replace it with another value? `/opt/qbittorrent/unrarall/unrarall`

**Comment by johnwchambers** [comment]
Yes, it's accurate. You have to pull that down from https://github.com/arfoll/unrarall. You can place it wherever you want, I just had it loaded there since qbit was the only thing that required it.

I can't remember if I had to load unrar as well, but if so I used the 'Nux Desktop EL7' repo from http://li.nux.ro/repos.html.

**Comment by morganzero** [comment]
Awesome. Thanks alot for clarifying :)

**Comment by mdhiggins** [comment]
Updated to include that information in the wiki and moved the unrar path to the environment variable `unrarpath`

**Comment by morganzero** [comment]
@johnwchambers If I may ask, assuming you have tested it with both *arrs. How did you get the *arrs to pick up the converted files?

**Comment by mdhiggins** [comment]
The script calls qBittorrentPostProcess.py which notifies the downloader to process the directory as part of its usual function

**Comment by morganzero** [comment]
> The script calls qBittorrentPostProcess.py which notifies the downloader to process the directory as part of its usual function

Sweet! Thanks.

**Comment by morganzero** [comment]
```![image](https://user-images.githubusercontent.com/57449785/116879679-38191c00-ac21-11eb-9a73-2574889cb90f.png)```
Isn't `requests` installed with the sma-mod?

**Comment by mdhiggins** [comment]
Yes but only within the virtual environment, are you using that as your pythonpath?

**Comment by morganzero** [comment]
> Yes but only within the virtual environment, are you using that as your pythonpath?

Yes, I guess so. This is what my script looks like:
```
#!/bin/sh

torrentid=$6
torrentname=$5
torrentpath=$4
torrentrootpath=$3
torrenttracker=$2
torrentcategory=$1

pathextraction=/mnt/completed/torrent/extracted
pathconversion=/mnt/completed/torrent/converted

pythonpath=/usr/local/sma/venv/bin/python3
smapath=/usr/local/sma
unrarpath=/opt/appdata/qbittorrent/unrarall/unrarall

if [ "$torrentcategory" = "bypass" ]; then
    #echo "skipping this since it's in the bypass category"
    exit 0
fi

if [[ -d "$torrentrootpath" ]]; then
    #echo "$torrentrootpath" + " is a directory"
    mkdir "$pathextraction/$torrentname"
    mkdir "$pathconversion/$torrentname"
    "$unrarpath" -v -o "$pathextraction/$torrentname" "$torrentrootpath"
    extracted=$?
    wait $!
    if [ $extracted -eq 0 ]; then
        if [[ -n $(find "$pathextraction/$torrentname" -type f -size +50M) ]]; then
            "$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$pathextraction/$torrentname" "$pathextraction/$torrentname" "$torrentname" "$torrentid"
        else
            "$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$torrentrootpath" "$torrentpath" "$torrentname" "$torrentid"
        fi
    else
        "$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$torrentrootpath" "$torrentpath" "$torrentname" "$torrentid"
    fi
    rm -rf "$pathextraction/$torrentname"
elif [[ -f "$torrentpath" ]]; then
    #echo "$torrentpath" + " is a file"
    "$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$torrentrootpath" "$torrentpath" "$torrentname" "$torrentid"
fi

exit 0
```

**Comment by mdhiggins** [comment]
Yeah should be installed then, if you delete your SMA folder and restart the container that should rerun the installation routine and maybe fix it

**Comment by morganzero** [comment]
I'll try that. Thanks!

**Comment by morganzero** [comment]
> Yeah should be installed then, if you delete your venv folder inside the SMA folder and restart the container that should rerun the installation routine and maybe fix it

I tried that now and I also recreated the qbit container. This is what I'm getting now:
```

[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 30-config: executing... 


[cont-init.d] 30-config: exited 0.


[cont-init.d] 90-sma-config: executing... 


E: Unable to locate package python-pymediainfo


Traceback (most recent call last):


  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main


    return _run_code(code, main_globals, None,


  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code


    exec(code, run_globals)


  File "/config/.local/lib/python3.8/site-packages/pip/__main__.py", line 21, in <module>


    from pip._internal.cli.main import main as _main


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 8, in <module>


    from pip._internal.cli.autocompletion import autocomplete


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>


    from pip._internal.cli.main_parser import create_main_parser


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>


    from pip._internal.cli import cmdoptions


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 20, in <module>


    from pip._vendor.packaging.utils import canonicalize_name


  File "/config/.local/lib/python3.8/site-packages/pip/_vendor/packaging/utils.py", line 9, in <module>


    from .tags import Tag, parse_tag


  File "/config/.local/lib/python3.8/site-packages/pip/_vendor/packaging/tags.py", line 7, in <module>


    import distutils.util


ModuleNotFoundError: No module named 'distutils.util'


Traceback (most recent call last):


  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main


    return _run_code(code, main_globals, None,


  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code


    exec(code, run_globals)


  File "/config/.local/lib/python3.8/site-packages/pip/__main__.py", line 21, in <module>


    from pip._internal.cli.main import main as _main


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 8, in <module>


    from pip._internal.cli.autocompletion import autocomplete


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>


    from pip._internal.cli.main_parser import create_main_parser


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>


    from pip._internal.cli import cmdoptions


  File "/config/.local/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 20, in <module>


    from pip._vendor.packaging.utils import canonicalize_name


  File "/config/.local/lib/python3.8/site-packages/pip/_vendor/packaging/utils.py", line 9, in <module>


    from .tags import Tag, parse_tag


  File "/config/.local/lib/python3.8/site-packages/pip/_vendor/packaging/tags.py", line 7, in <module>


    import distutils.util


ModuleNotFoundError: No module named 'distutils.util'


Traceback (most recent call last):


  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main


    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)


  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details


    return _get_module_details(pkg_main_name, error)


  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details


    __import__(pkg_name)


  File "/config/.local/lib/python3.8/site-packages/virtualenv/__init__.py", line 3, in <module>


    from .run import cli_run, session_via_cli


  File "/config/.local/lib/python3.8/site-packages/virtualenv/run/__init__.py", line 14, in <module>


    from .plugin.creators import CreatorSelector


  File "/config/.local/lib/python3.8/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>


    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin


  File "/config/.local/lib/python3.8/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>


    from virtualenv.create.creator import Creator


  File "/config/.local/lib/python3.8/site-packages/virtualenv/create/creator.py", line 15, in <module>


    from virtualenv.discovery.cached_py_info import LogCmd


  File "/config/.local/lib/python3.8/site-packages/virtualenv/discovery/cached_py_info.py", line 16, in <module>


    from virtualenv.discovery.py_info import PythonInfo


  File "/config/.local/lib/python3.8/site-packages/virtualenv/discovery/py_info.py", line 16, in <module>


    from distutils import dist


ImportError: cannot import name 'dist' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)


/var/run/s6/etc/cont-init.d/90-sma-config: line 25: /usr/local/sma/venv/bin/pip: No such file or directory


/var/run/s6/etc/cont-init.d/90-sma-config: line 74: /usr/local/sma/venv/bin/python3: No such file or directory


[cont-init.d] 90-sma-config: exited 127.


[cont-init.d] 99-custom-scripts: executing... 


[custom-init] no custom files found exiting...


[cont-init.d] 99-custom-scripts: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.
```

**Comment by mdhiggins** [comment]
Hm looks like that package isn't available on focal, I'm gonna fix that and update the container now, just wait a few minutes for the container to rebuild

**Comment by mdhiggins** [comment]
Done, rebuild container and try again

**Comment by morganzero** [comment]
> Done, rebuild container and try again

It finally executes the script. But it fails when trying to call PYTHON-QBITTORRENT.
```
All OK


ok


1 rar files found and extracted


2021-05-03 16:18:02 - qBittorrentPostProcess - INFO - qBittorrent post processing started.


2021-05-03 16:18:02 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3


2021-05-03 16:18:02 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.


2021-05-03 16:18:02 - qBittorrentPostProcess - ERROR - Python module PYTHON-QBITTORRENT is required. Install with 'pip install python-qbittorrent' then try again.


Traceback (most recent call last):


  File "/usr/local/sma/qBittorrentPostProcess.py", line 57, in <module>


    from qbittorrent import Client


ModuleNotFoundError: No module named 'qbittorrent'


2021-05-03 16:18:02 - qBittorrentPostProcess - ERROR - Unexpected exception.


Traceback (most recent call last):


  File "/usr/local/sma/qBittorrentPostProcess.py", line 57, in <module>


    from qbittorrent import Client


ModuleNotFoundError: No module named 'qbittorrent'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/usr/local/sma/qBittorrentPostProcess.py", line 60, in <module>


    sys.exit(1)


SystemExit: 1```

**Comment by mdhiggins** [comment]
Added those missing dependencies as well for both qbittorrent and deluge

**Comment by morganzero** [comment]
Woohoo! Let's test :)

**Comment by morganzero** [comment]
This is how far I got. Not sure what it's missing this time.

```
2021-05-03 19:42:43 - qBittorrentPostProcess - INFO - qBittorrent post processing started.,
2021-05-03 19:42:43 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3,
2021-05-03 19:42:43 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.,
2021-05-03 19:42:43 - qBittorrentPostProcess - INFO - Performing conversion,
2021-05-03 19:42:44 - qBittorrentPostProcess - ERROR - No output files generated for the entirety of this mutli file torrent, aborting.,
2021-05-03 19:42:44 - qBittorrentPostProcess - ERROR - Unexpected exception.,
Traceback (most recent call last):,
  File "/usr/local/sma/qBittorrentPostProcess.py", line 132, in <module>,
    sys.exit(1),
SystemExit: 1,
```

**Comment by mdhiggins** [comment]
No files are being converted for some unknown reason, I would make sure your FFMPEG binaries can be executed (ffmpeg and ffprobe) and then trying running a file through manual.py to see if you can get an error

**Comment by morganzero** [comment]
> No files are being converted for some unknown reason, I would make sure your FFMPEG binaries can be executed (ffmpeg and ffprobe) and then trying running a file through manual.py to see if you can get an error

I bound then like this in the container.
![B09EA4D5-4CE1-407A-9A3F-1D16B034D89A](https://user-images.githubusercontent.com/57449785/116915008-c7d3c000-ac4b-11eb-89d2-cca0020f8723.jpeg)

And this is the autoProcess.ini paths for them
```
[Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
```
Looks correct?

**Comment by mdhiggins** [comment]
It may be a permissions issue, you don't have to bind FFMPEG its downloaded, installed, and permissions are automatically adjusted as part of sma-mod though, but if it detects that you already have ffmpeg installed it won't go through that process so you may be inadvertently messing it up by binding it

**Comment by morganzero** [comment]
Reason I did that was because container logs said it couldn't find ffmpeg/ffprobe. I pasted logs here.

```
[cont-init.d] 90-sma-config: executing... ,
/var/run/s6/etc/cont-init.d/90-sma-config: line 62: wget: command not found,
tar (child): /tmp/ffmpeg.tar.xz: Cannot open: No such file or directory,
tar (child): Error is not recoverable: exiting now,
tar: Child returned status 2,
tar: Error is not recoverable: exiting now,
chown: cannot access '/usr/local/bin/ffmpeg': No such file or directory,
chown: cannot access '/usr/local/bin/ffprobe': No such file or directory,
chmod: cannot access '/usr/local/bin/ffmpeg': No such file or directory,
chmod: cannot access '/usr/local/bin/ffprobe': No such file or directory,
[cont-init.d] 90-sma-config: exited 0.,
```

**Comment by mdhiggins** [comment]
That might have been from earlier when the apt-get install command was failing, wget should be included in that initial package request, is it still giving you that error?

**Comment by morganzero** [comment]
Yeah. This one I got just before I posted it for you. I had removed bindings and rebuilt.

**Comment by mdhiggins** [comment]
Hm that doesn't make any sense, does wget work if you just try it from the command line?

**Comment by morganzero** [comment]
Is it ffmpeg.tar.xz or GZ?

**Comment by mdhiggins** [comment]
Should matter, the command that's failing is wget
`wget: command not found,`

**Comment by morganzero** [comment]
From inside the container I get:
`bash: wget: command not found`

**Comment by mdhiggins** [comment]
Does running apt-get install wget do anything?

**Comment by morganzero** [comment]
Looks like it doesn't wanna be friends with wget.

```
***@***.***:/# apt-get install wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package wget
```

**Comment by mdhiggins** [comment]
https://packages.ubuntu.com/focal/wget

Looks like wget should be available. If you run `apt-get update` first then try `apt-get install wget` does that help?

**Comment by morganzero** [comment]
Yeah I just ran this
apt-get update && apt-get install apt-file -y && apt-file update && apt-get install wget -y

And it seems to be working now. Going to try and execute the script once again and see if it works now :)

**Comment by mdhiggins** [comment]
The question is how did this fail in the first place. The 90-sma-config includes the apt-get update and apt-get install wget options so somehow they must have been skipped, which makes me worry you might be missing other dependent packages as well

The script checks to see if the virtual environment has been created to determine if it should run these steps, I'm going to decouple a few of the dependency checks from this and update the container

**Comment by morganzero** [comment]
Okay, so everytime I rebuild the container wget stops working. Perhaps adding in apt-get update to your mod is necessary?

**Comment by morganzero** [comment]
This is the log if it helps

```
[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing...

[cont-init.d] 30-config: exited 0.

[cont-init.d] 90-sma-config: executing...

/var/run/s6/etc/cont-init.d/90-sma-config: line 62: wget: command not found

tar (child): /tmp/ffmpeg.tar.xz: Cannot open: No such file or directory

tar (child): Error is not recoverable: exiting now

tar: Child returned status 2

tar: Error is not recoverable: exiting now

chown: cannot access '/usr/local/bin/ffmpeg': No such file or directory

chown: cannot access '/usr/local/bin/ffprobe': No such file or directory

chmod: cannot access '/usr/local/bin/ffmpeg': No such file or directory

chmod: cannot access '/usr/local/bin/ffprobe': No such file or directory

[cont-init.d] 90-sma-config: exited 0.

[cont-init.d] 99-custom-scripts: executing...

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

```

**Comment by mdhiggins** [comment]
apt-get update is included its one of the first lines, it's probably not getting executed though and I just updated the conditions to hopefully help, the container rebuild just finished

**Comment by morganzero** [comment]
Let's try again :)

**Comment by morganzero** [comment]
Container just got rebuilt. Took a while, longer than usual.

Just thought I'd share the logs with you with the warnings I got before I try and execute the script.
```
[mod-init] Attempting to run Docker Modification Logic

[mod-init] Applying mdhiggins/sma-mod:latest files to container

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing...

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing...


-------------------------------------

         _         ()

        | |  ___   _    __

        | | / __| | |  /  \

        | | \__ \ | | | () |

        |_| |___/ |_|  \__/



Brought to you by linuxserver.io

-------------------------------------


To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    1000

User gid:    1000

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing...

[cont-init.d] 30-config: exited 0.

[cont-init.d] 90-sma-config: executing...

WARNING: The directory '/config/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

WARNING: The directory '/config/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

[cont-init.d] 90-sma-config: exited 0.

[cont-init.d] 99-custom-scripts: executing...

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.
```

**Comment by mdhiggins** [comment]
Looks like things worked this time without any serious errors, good sign

**Comment by morganzero** [comment]
I don't think you understand how happy these lines make me 😂

```
2021-05-03 21:16:05 - resources.mediaprocessor - INFO - Starting conversion.

2021-05-03 21:16:05 - resources.mediaprocessor - INFO - FFmpeg command:

2021-05-03 21:16:05 - resources.mediaprocessor - INFO - ======================

2021-05-03 21:16:05 - resources.mediaprocessor - INFO - /usr/local/bin/ffmpeg -fix_sub_duration -i /mnt/completed/torrent/extracted/video.mkv
```
Although, I cannot see the process bar so I don't really know if it's converting.
```
2021-05-03 21:16:05 - resources.mediaprocessor - INFO - ======================
```
Possible to add?

**Comment by mdhiggins** [comment]
Nah the technique that's used to write/rewrite the line for the progress bar doesn't translate over nicely into logs for other applications, but glad its working!

**Comment by morganzero** [comment]
Thanks alot for your support!

**Comment by morganzero** [comment]
Would this exact process and script work if I  switched out `$smapath/qBittorrentPostProcess.py` to `$smapath/delugePostProcess.py` ?

**Comment by morganzero** [comment]
Not sure if this is a big issue. It successfully competed the conversion, however it failed at deleting the temporary folder.
```
2021-05-03 22:29:24 - resources.mediaprocessor - INFO - ======================

2021-05-03 22:38:52 - resources.mediaprocessor - INFO - /mnt/completed/torrent/radarr/785361a14565b462ab412812ba57da48eafa5bd0-convert/video.mkv created.

2021-05-03 22:38:52 - qBittorrentPostProcess - INFO - Passing /mnt/completed/torrent/radarr/785361a14565b462ab412812ba57da48eafa5bd0-convert directory to Radarr.

2021-05-03 22:38:52 - autoprocess.radarr - INFO - Radarr notifier started.

2021-05-03 22:38:52 - autoprocess.radarr - INFO - Requesting Radarr to scan directory '/mnt/completed/torrent/radarr/785361a14565b462ab412812ba57da48eafa5bd0-convert'.

2021-05-03 22:38:54 - autoprocess.radarr - INFO - Radarr response: queued.

2021-05-03 22:38:54 - qBittorrentPostProcess - ERROR - Unable to delete temporary directory

Traceback (most recent call last):

 File "/usr/local/sma/qBittorrentPostProcess.py", line 200, in <module>

   os.rmdir(delete_dir)

OSError: [Errno 39] Directory not empty: '/mnt/completed/torrent/radarr/785361a14565b462ab412812ba57da48eafa5bd0-convert
```

**Comment by morganzero** [comment]
Found a duplicate entry in line 31. Should one of them be `$pathconversion/$torrentname`?. Cause right now, the script converts the file inside of the extraction path and calls *arr to scan the extraction path as well.

`"$pythonpath" "$smapath/qBittorrentPostProcess.py" "$torrentcategory" "$torrenttracker" "$pathextraction/$torrentname" "$pathextraction/$torrentname" "$torrentname" "$torrentid"
`

**Comment by johnwchambers** [comment]
No, it's not a duplicate. There is a check (line 30) to see if there is a file greater than 50MB in size before passing it to either arr application. If after the extraction there is no file greater than 50MB, we're assuming nothing valid was extracted because either there was no archive in the first place or because what was extracted was too small.

So line 31 is if there was a "successful" extraction and line 33 is if there wasn't one and to continue trucking along.

**Comment by morganzero** [comment]
> *** Sorry for the edits, long day at the office and want to make sure my wording is right lol***
> 
> No, it's not a duplicate.
> 
> Lines 29-35 are for when unrarall successfully extracted something. There is a check (line 30) to see if there is a file greater than 50MB in size before passing the extracted path to either arr application. If after the extraction there is no file greater than 50MB, just pass the original path to either arr application. We're assuming that even though an extraction occurred that since the file is so small it's probably wrong anyway.
> 
> Lines 36 - 37 are if unrarall did NOT successfully extract anything. So just pass along the original paths.

Oh, no worries @johnwchambers , I'm an edit God lol

That makes sense. Thank you for clarifying mate. I do wonder because I get `ERROR - Unable to delete temporary directory` after a successful conversion, where it seems it has been converting in extraction path rather than conversion path. Or have I misunderstood the process? :)

And also, is it possible to remove the "-convert" flag from the end of the filename after a successful conversion? Cause *arr puts "-convert" as a release group lol

**Comment by johnwchambers** [comment]
It probably has to do with the qbit section where I have the output directory already defined to somewhere else. My setup is not super complicated but not a peach to navigate when I was first getting it going lol. If you don't have the output-directory set to something different than the extracted directory then it will convert the file in place and add the "-convert" to the names of folders and files if I recall.

However, if you have that output-directory defined, conversions of extracted (or unextracted) files are done on the fly to this spot. This path is what eventually gets passed to the arr application for ingest. This way my original qbit files will seed for as long as I see fit and any extracted files etc won't mess up their original folder/file structures.

Extracted folders are always cleaned up successfully, the converted folder sometimes has leftover hanging fruit due to more than just the converted file being leftover. This is where I see some errors about deleting the directory as well but I just look past it. This is also a good thing too since I can review what's left if I notice something wasn't pulled in when it should have been. Sometimes Korean TV shows give me issues due to how they name their releases so in the end it works out for me this way.

A copy of my full autoProcess.ini is below as well for comparison. Feel free to email me directly (my email is on my github page) if you want to take this conversation offline. It's been a pleasure thus far! ^^

	[Converter]
	ffmpeg = /usr/bin/ffmpeg
	ffprobe = /usr/bin/ffprobe
	threads = 0
	hwaccels = dxva2, cuvid, qsv, d3d11va, cuda
	hwaccel-decoders = h264_cuvid, h265_cuvid, hevc_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
	output-directory =
	output-format = mp4
	output-extension = mp4
	temp-extension =
	ignored-extensions = nfo, ds_store
	copy-to =
	move-to =
	delete-original = True
	sort-streams = False
	process-same-extensions = True
	force-convert = False
	post-process = False
	preopts =
	postopts = -max_muxing_queue_size, 9999
	minimum-size = 0
	detailed-progress = False
	hwdevices = vaapi:/dev/dri/renderD128
	hwaccel-output-format = vaapi:vaapi
	wait-post-process = True
	bypass-if-copying-all = False
	opts-separator = ,
	regex-directory-replace = [^\w\-_\. ]

	[Permissions]
	chmod = 0777
	uid = -1
	gid = -1

	[Metadata]
	relocate-moov = True
	full-path-guess = True
	tag = True
	tag-language = eng
	download-artwork = False
	preserve-source-disposition = True
	sanitize-disposition =
	strip-metadata = False

	[Video]
	codec = h264_nvenc, h264, x264, h265_nvenc, hevc, h265, x265
	bitrate = 0
	crf = -1
	crf-profiles = 0:23:4.5M:12M,4100:21:8M:24M,8000:17:10M:30M
	max-width = 0
	profile =
	max-level = 0.0
	pix-fmt =
	max-bitrate = 10000
	filter =
	force-filter = False
	codec-parameters =
	dynamic-parameters = True
	preset =
	bitrate-ratio =

	[Audio]
	codec = ac3
	languages = eng, kor, jpn, chi, zho, deu, ger
	default-language =
	channel-bitrate = 128
	max-channels = 0
	prefer-more-channels = True
	filter =
	sample-rates =
	copy-original = False
	first-track-of-language = False
	allow-language-relax = True
	aac-adtstoasc = False
	ignore-truehd = mp4, m4v
	first-stream-of-language = False
	default-more-channels = True
	max-bitrate = 0
	force-filter = False
	ignored-dispositions =
	unique-dispositions = False

	[Universal Audio]
	codec = aac
	first-track-only = False
	move-last = False
	filter =
	first-stream-only = False
	move-after = False
	channel-bitrate = 128
	force-filter = False

	[Subtitle]
	codec = srt
	codec-image-based =
	languages = eng, kor
	default-language =
	encoding = UTF-8
	burn-subtitles = False
	embed-subs = False
	embed-image-subs = False
	embed-only-internal-subs = False
	attachment-codec =
	first-stream-of-language = False
	ignore-embedded-subs = False
	burn-dispositions =
	filename-dispositions = forced
	ignored-dispositions =
	unique-dispositions = False

	[Sonarr]
	host = localhost
	port = 8989
	apikey = asdfasdfasdf
	ssl = False
	webroot =
	force-rename = False
	rescan = True
	block-reprocess = False

	[Radarr]
	host = localhost
	port = 7878
	apikey = asdfasdfasdf
	ssl = False
	webroot =
	force-rename = False
	rescan = True
	block-reprocess = False

	[Sickbeard]
	host = localhost
	port = 8081
	ssl = False
	apikey =
	webroot =
	username =
	password =

	[Sickrage]
	host = localhost
	port = 8081
	ssl = False
	apikey =
	webroot =
	username =
	password =

	[CouchPotato]
	host = localhost
	port = 5050
	username =
	password =
	apikey =
	delay = 65
	method = renamer
	delete-failed = False
	ssl = False
	webroot =

	[SABNZBD]
	convert = True
	sickbeard-category = sickbeard
	sickrage-category = sickrage
	couchpotato-category = couchpotato
	sonarr-category = tv
	radarr-category = movie
	bypass-category = bypass
	output-directory = None
	path-mapping =

	[Deluge]
	couchpotato-label = couchpotato
	sickbeard-label = sickbeard
	sickrage-label = sickrage
	sonarr-label = tv
	radarr-label = movie
	bypass-label = bypass
	convert = True
	host = localhost
	port = 58846
	username = mp4automator
	password = mp4automator
	output-directory = /dwnldr/tor/converted
	remove = False
	path-mapping =

	[qBittorrent]
	couchpotato-label = couchpotato
	sickbeard-label = sickbeard
	sickrage-label = sickrage
	sonarr-label = tv
	radarr-label = movie
	bypass-label = bypass
	convert = True
	action-before =
	action-after =
	host = localhost
	port = 8080
	ssl = False
	username =
	password =
	output-directory = /dwnldr/tor/converted
	path-mapping =

	[uTorrent]
	couchpotato-label = couchpotato
	sickbeard-label = sickbeard
	sickrage-label = sickrage
	sonarr-label = sonarr
	radarr-label = radarr
	bypass-label = bypass
	convert = True
	webui = False
	action-before = stop
	action-after = removedata
	host = localhost
	ssl = False
	port = 8080
	username =
	password =
	output-directory =
	path-mapping =

	[Plex]
	host = localhost
	port = 32400
	refresh = False
	token = asdfasdf

	[HDR]
	space = bt2020nc
	transfer = smpte2084
	primaries = bt2020
	filter =
	force-filter = False
	codec-parameters =
	pix-fmt =
	preset =
	codec =
	profile =

	[Subtitle.Subliminal]
	download-subs = False
	download-hearing-impaired-subs = False
	providers =

	[Audio.ChannelFilters]
	6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

	[Subtitle.Subliminal.Auth]
	opensubtitles =
	tvsubtitles =

**Comment by morganzero** [comment]
> It probably has to do with the qbit section where I have the output directory already defined to somewhere else. My setup is not super complicated but not a peach to navigate when I was first getting it going lol. If you don't have the output-directory set to something different than the extracted directory then it will convert the file in place and add the "-convert" to the names of folders and files if I recall.
> 
> However, if you have that output-directory defined, conversions of extracted (or unextracted) files are done on the fly to this spot. This path is what eventually gets passed to the arr application for ingest. This way my original qbit files will seed for as long as I see fit and any extracted files etc won't mess up their original folder/file structures.
> 
> Extracted folders are always cleaned up successfully, the converted folder sometimes has leftover hanging fruit due to more than just the converted file being leftover. This is where I see some errors about deleting the directory as well but I just look past it. This is also a good thing too since I can review what's left if I notice something wasn't pulled in when it should have been. Sometimes Korean TV shows give me issues due to how they name their releases so in the end it works out for me this way.
> 
> A copy of my full autoProcess.ini is below as well for comparison. Feel free to email me directly (my email is on my github page) if you want to take this conversation offline. It's been a pleasure thus far! ^^
> 
> ```
> [Converter]
> ffmpeg = /usr/bin/ffmpeg
> ffprobe = /usr/bin/ffprobe
> threads = 0
> hwaccels = dxva2, cuvid, qsv, d3d11va, cuda
> hwaccel-decoders = h264_cuvid, h265_cuvid, hevc_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
> output-directory =
> output-format = mp4
> output-extension = mp4
> temp-extension =
> ignored-extensions = nfo, ds_store
> copy-to =
> move-to =
> delete-original = True
> sort-streams = False
> process-same-extensions = True
> force-convert = False
> post-process = False
> preopts =
> postopts = -max_muxing_queue_size, 9999
> minimum-size = 0
> detailed-progress = False
> hwdevices = vaapi:/dev/dri/renderD128
> hwaccel-output-format = vaapi:vaapi
> wait-post-process = True
> bypass-if-copying-all = False
> opts-separator = ,
> regex-directory-replace = [^\w\-_\. ]
> 
> [Permissions]
> chmod = 0777
> uid = -1
> gid = -1
> 
> [Metadata]
> relocate-moov = True
> full-path-guess = True
> tag = True
> tag-language = eng
> download-artwork = False
> preserve-source-disposition = True
> sanitize-disposition =
> strip-metadata = False
> 
> [Video]
> codec = h264_nvenc, h264, x264, h265_nvenc, hevc, h265, x265
> bitrate = 0
> crf = -1
> crf-profiles = 0:23:4.5M:12M,4100:21:8M:24M,8000:17:10M:30M
> max-width = 0
> profile =
> max-level = 0.0
> pix-fmt =
> max-bitrate = 10000
> filter =
> force-filter = False
> codec-parameters =
> dynamic-parameters = True
> preset =
> bitrate-ratio =
> 
> [Audio]
> codec = ac3
> languages = eng, kor, jpn, chi, zho, deu, ger
> default-language =
> channel-bitrate = 128
> max-channels = 0
> prefer-more-channels = True
> filter =
> sample-rates =
> copy-original = False
> first-track-of-language = False
> allow-language-relax = True
> aac-adtstoasc = False
> ignore-truehd = mp4, m4v
> first-stream-of-language = False
> default-more-channels = True
> max-bitrate = 0
> force-filter = False
> ignored-dispositions =
> unique-dispositions = False
> 
> [Universal Audio]
> codec = aac
> first-track-only = False
> move-last = False
> filter =
> first-stream-only = False
> move-after = False
> channel-bitrate = 128
> force-filter = False
> 
> [Subtitle]
> codec = srt
> codec-image-based =
> languages = eng, kor
> default-language =
> encoding = UTF-8
> burn-subtitles = False
> embed-subs = False
> embed-image-subs = False
> embed-only-internal-subs = False
> attachment-codec =
> first-stream-of-language = False
> ignore-embedded-subs = False
> burn-dispositions =
> filename-dispositions = forced
> ignored-dispositions =
> unique-dispositions = False
> 
> [Sonarr]
> host = localhost
> port = 8989
> apikey = asdfasdfasdf
> ssl = False
> webroot =
> force-rename = False
> rescan = True
> block-reprocess = False
> 
> [Radarr]
> host = localhost
> port = 7878
> apikey = asdfasdfasdf
> ssl = False
> webroot =
> force-rename = False
> rescan = True
> block-reprocess = False
> 
> [Sickbeard]
> host = localhost
> port = 8081
> ssl = False
> apikey =
> webroot =
> username =
> password =
> 
> [Sickrage]
> host = localhost
> port = 8081
> ssl = False
> apikey =
> webroot =
> username =
> password =
> 
> [CouchPotato]
> host = localhost
> port = 5050
> username =
> password =
> apikey =
> delay = 65
> method = renamer
> delete-failed = False
> ssl = False
> webroot =
> 
> [SABNZBD]
> convert = True
> sickbeard-category = sickbeard
> sickrage-category = sickrage
> couchpotato-category = couchpotato
> sonarr-category = tv
> radarr-category = movie
> bypass-category = bypass
> output-directory = None
> path-mapping =
> 
> [Deluge]
> couchpotato-label = couchpotato
> sickbeard-label = sickbeard
> sickrage-label = sickrage
> sonarr-label = tv
> radarr-label = movie
> bypass-label = bypass
> convert = True
> host = localhost
> port = 58846
> username = mp4automator
> password = mp4automator
> output-directory = /dwnldr/tor/converted
> remove = False
> path-mapping =
> 
> [qBittorrent]
> couchpotato-label = couchpotato
> sickbeard-label = sickbeard
> sickrage-label = sickrage
> sonarr-label = tv
> radarr-label = movie
> bypass-label = bypass
> convert = True
> action-before =
> action-after =
> host = localhost
> port = 8080
> ssl = False
> username =
> password =
> output-directory = /dwnldr/tor/converted
> path-mapping =
> 
> [uTorrent]
> couchpotato-label = couchpotato
> sickbeard-label = sickbeard
> sickrage-label = sickrage
> sonarr-label = sonarr
> radarr-label = radarr
> bypass-label = bypass
> convert = True
> webui = False
> action-before = stop
> action-after = removedata
> host = localhost
> ssl = False
> port = 8080
> username =
> password =
> output-directory =
> path-mapping =
> 
> [Plex]
> host = localhost
> port = 32400
> refresh = False
> token = asdfasdf
> 
> [HDR]
> space = bt2020nc
> transfer = smpte2084
> primaries = bt2020
> filter =
> force-filter = False
> codec-parameters =
> pix-fmt =
> preset =
> codec =
> profile =
> 
> [Subtitle.Subliminal]
> download-subs = False
> download-hearing-impaired-subs = False
> providers =
> 
> [Audio.ChannelFilters]
> 6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE
> 
> [Subtitle.Subliminal.Auth]
> opensubtitles =
> tvsubtitles =
> ```

Ah, thanks man I do appreciate you guys. I'm so happy I got torrents working again. Have been trying for over a year without success lol.

Thanks again!

**Comment by morganzero** [comment]
> Nah the technique that's used to write/rewrite the line for the progress bar doesn't translate over nicely into logs for other applications, but glad its working!

I see what you mean lol
![image](https://user-images.githubusercontent.com/57449785/117120124-3bccb000-ad93-11eb-920e-ebf57923c1f3.png)
But did you change something? Cause for some reason the progress bar started showing.

**Comment by morganzero** [comment]
The "resume" function seems broken for qBit in the autoProcess.ini. I have tried with and without SSL. Any thoughts?
```
[#####               ] 24% 2021-05-05 11:21:41 - autoprocess.radarr - INFO - Radarr response: queued.
2021-05-05 11:21:41 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "/usr/local/sma/qBittorrentPostProcess.py", line 187, in <module>
    qb.resume(torrent_hash)
  File "/usr/local/sma/venv/lib/python3.8/site-packages/qbittorrent/client.py", line 494, in resume
    return self._post('torrents/resume', data={'hashes': infohash.lower()})
  File "/usr/local/sma/venv/lib/python3.8/site-packages/qbittorrent/client.py", line 64, in _post
    return self._request(endpoint, 'post', data, **kwargs)
  File "/usr/local/sma/venv/lib/python3.8/site-packages/qbittorrent/client.py", line 88, in _request
    request.raise_for_status()
  File "/usr/local/sma/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://qbit:8098/api/v2/torrents/resume
```

**Comment by johnwchambers** [comment]
Double-check your Web UI settings in qbit and make sure the username and password you have defined in your autoProcess.ini match. If all else fails you can bypass authentication if qbit is on the same system as the sma stuff or let it be bypassed by IP. 

Reference qbit Web UI settings for my setup is below.

![image](https://user-images.githubusercontent.com/752262/117139816-a27bb900-ade7-11eb-802f-f6641f7cb2c6.png)

**Comment by morganzero** [comment]
Thanks pal, I’ll test that out :)

**Comment by morganzero** [comment]
Hi guys, I'm getting this error now in container logs.

I have tried the following:
* rebuild container
* deleting venv folder & rebuilding container
* reinstalling wget inside container

Unfortunately none of that worked. Seems like there is an error in the unpacking process. Got any ideas?
```
[mod-init] Attempting to run Docker Modification Logic

[mod-init] Applying mdhiggins/sma-mod:latest files to container


gzip: stdin: not in gzip format

tar: Child returned status 1

tar: Error is not recoverable: exiting now

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... ```

**Comment by mdhiggins** [comment]
Docker updated their API and broke docker-mods. Linuxserver is working on a fix.

**Comment by morganzero** [comment]
Oh I see, out of our hands then. Any way I can track the their progress with this issue?

**Comment by mdhiggins** [comment]
https://github.com/linuxserver/docker-mods/issues/160

Seems like a fix is in the work and will make its way out to the various linuxserver images shortly

**Comment by morganzero** [comment]
Thanks! :)

**Comment by morganzero** [comment]
FYI. Fixed now.

**Comment by mdhiggins** [comment]
Tested on deluge, still getting the error. What container? It might trickle down to various containers at different times

**Comment by morganzero** [comment]
I'm using qBit. Rebuilt this morning with bad results and then again by the time I commented last.
