### ISSUE TITLE
NZBGet & Couchpotato failed download handling

### ISSUE THREAD

**Issue by javvydawg** [mdhiggins/sickbeard_mp4_automator#384]
Not sure what I am doing wrong I followed the steps on the read me file and edited main.py to point to my script but Couchpotato just does not mark download as failed. One question though I am on Linux and have the path as "//home//brix//mp4_automator//" am I supposed to use double slashes? I tried with single slashes and double but I get the same error on nzbget but the logs on Couchpotato show nothing. See attached picture. Thank you for any help
![screenshot_2015-12-28-12-10-36](https://cloud.githubusercontent.com/assets/16467698/12024771/90e15826-ad5c-11e5-8de0-176d039914c0.png)

**Comment by mdhiggins** [comment]
You only need to do double slashes for backslashes, not for forward slashes, so just use `/home/birx/mp4_automator/`

As far as the error you're getting goes, this is caused by a problem with the JSON object being returned when NZBGetPostProcess is trying to communicate with Couch Potato and let CP know the download has completed. This is likely caused by something not being properly setup under the [CouchPotato] settings of your autoProcess.ini file. I would verify all of those settings are correct and try again.

**Comment by javvydawg** [comment]
Ok thanks for the help. Another thing I'm not so clear about, is the path supposed to be in quotes? Path= "/home/brix/mp4_automaton/" ? I'm going to reinstall Couchpotato then redo the settings and see if that will help. I'll post back with an update thank you again for this amazing script and support

**Comment by mdhiggins** [comment]
Let me know how it goes.

And yes the path should be in quotes. You’re directly editing the python there, so it has to obey standard python syntax (string needs to be in quotes).

And you’re very welcome :)

**Comment by javvydawg** [comment]
Ok I corrected the path so I know that should not be an issue but Couchpotato still won't mark dowanload as failed and retry with a new nzb. I double checked my Couchpotato settings in the config file and they are correct. Double checked api as well. (Please see attached picture) Any ideas what it could be?? I have team viewer if your willing to check it out. :)

**Comment by mdhiggins** [comment]
Just looking at your screenshot, I'm noticing your couch potato port is 5050 but it looks like you're accessing it via the browser without a port specified. I'm wondering if maybe with your webroot type setup if your port is 80 and not 5050?

**Comment by javvydawg** [comment]
Well it works with both ports 80 and 5050. 
![screenshot_2015-12-29-19-27-52](https://cloud.githubusercontent.com/assets/16467698/12045949/b25fd016-ae62-11e5-9464-7499939165f5.png)
Post processing works fine with sonarr even failed download handling. Its just Couchpotato that is giving me problems. Maybe a permissions issue ??

**Comment by mdhiggins** [comment]
If you open your NZBGet log to the line where it says "auto process.autoProcessMovie - INFO - Opening URL ..." and copy and paste that URL into your browser, does it work and give you a JSON output or does it give you an error? I think that's where the problem is coming from

**Comment by mdhiggins** [comment]
Wait looked closer at your log and I'm realizing this has nothing to do with my script failing, this is all failing because your download is corrupt, I hadn't looked far enough down. See the part where it says "_brokenlog.txt exists"

That means when it tried to extract/repair the file there was a corrupt component and it was unable to do so, its just a bad download. Probably a bad NZB. They're way more common for movies than for TV shows which is probably why Sonarr is working.

**Comment by javvydawg** [comment]
Oh I'm sorry if I wasn't clear in my explanation, it is a bad download but my issue is that Couchpotato is not sending a new nzb when it fails. In the logs i see that it is recognized as failed 

NZBGetPostProcess: 2015-12-29 19:28:56 - autoprocess.autoProcessMovie - INFO - Download of Divergent.2014.BluRay.Repack.1080p.x264.DTS-HD.MA.7.1-HDW.cp(tt1840309).nzb has failed.

and then it tries to look for another release 

NZBGetPostProcess: 2015-12-29 19:28:56 - autoprocess.autoProcessMovie - INFO - Trying to re-cue the next highest ranked release.

but after that i guess couchpotato stops responding or i think it just cant recognize the movie id?? i tried going to that url and this comes out

**Comment by mdhiggins** [comment]
Alright I just pushed some updates to autoProcessMovie.py that should hopefully fix this error and allow CP to trigger a fresh download. Give that a try and lemme know how it goes.

**Comment by javvydawg** [comment]
ok i redownloaded the script replaced files and the config file. re-ran the download and i get the almost the same error.

![untitled](https://cloud.githubusercontent.com/assets/16467698/12058493/8f0b6aea-af01-11e5-9ba2-f383c48b68b2.png)

**Comment by mdhiggins** [comment]
Looks like I made a mistake with that patch and didn't have the JSON hierarchy correct. Just pushed another update. Sorry about that. Give it another try if you'd be so kind.

**Comment by javvydawg** [comment]
ok now it is showing this as an error.

![untitled2](https://cloud.githubusercontent.com/assets/16467698/12059194/80669f6e-af0b-11e5-8c09-892335b7acf2.png)

**Comment by javvydawg** [comment]
By the way is there a donation link? I would like to at least buy you a beer for helping me with this.

**Comment by javvydawg** [comment]
i just ran into another failed download but this time its a completely different error. 

![untitled3](https://cloud.githubusercontent.com/assets/16467698/12059884/f5b2ec3e-af18-11e5-9072-1795743243c3.png)

**Comment by mdhiggins** [comment]
Alright, further bug chasing on the new error. Should be resolved and should now trigger a new scan, update again to the latest version. As far as the second error you're reporting goes, that's a PAR check failure. This causes a script abort much earlier than the previous error so the autoProcessMovie script isn't actually even triggered. No post processing actually takes place.

For your side note question about it showing up as N/A, I think that's just a couch potato bug, I have had that happen intermittently with certain movies that aren't even post-processed.

And finally, if you'd like to donate my paypal is tehpsyc@gmail.com; and a beer is always appreciated!

**Comment by javvydawg** [comment]
Updated to latest version of script and still same error. Could nzbget be the issue???  Should i try switching to sabnzbd and see if that helps??

![screenshot_2015-12-31-11-01-42](https://cloud.githubusercontent.com/assets/16467698/12067405/4a6f6b04-afae-11e5-8153-a50cf3944948.png)

**Comment by mdhiggins** [comment]
Shit my connection timed out when syncing the last commit and it didn't go through. Just resynced and it worked this time. That's why you were still getting the error. Give it another try. And stay with NZBGet I like it a lot more.

**Comment by javvydawg** [comment]
Ok thanks it worked this time but there's a problem with the URL ... We're almost there tho lol


![screenshot_2015-12-31-12-44-53](https://cloud.githubusercontent.com/assets/16467698/12068164/7e2ad880-afbc-11e5-9eaa-bdd9e038fda4.png)

**Comment by mdhiggins** [comment]
Almost there indeed haha.

Alright, looks like CP had updated the URL in a recent version from what it previously was. Just pushed a change that should fix the URL

**Comment by javvydawg** [comment]
Ok now it's showing this. Not sure what the problem is now. It didn't change the release to failed still shows snatched.

![screenshot_2016-01-01-10-40-23](https://cloud.githubusercontent.com/assets/16467698/12071804/3d845a96-b074-11e5-9783-5bc3dd1c0fa2.png)

**Comment by mdhiggins** [comment]
Does this particular release have any further download options queued?

**Comment by mdhiggins** [comment]
Found another bug that was causing the success: false error. Update and give it a try, I'm getting success: true on my end now

**Comment by javvydawg** [comment]
Ok now I have an issue with nzbget skipping the script due to a par check failure? I try to force post processing but I get the same result. 

![screenshot_2016-01-10-12-33-39](https://cloud.githubusercontent.com/assets/16467698/12223832/dcc62a3e-b796-11e5-81ed-3d86d86ba107.png)

So I switched to sabnzbd because it has an option to force post process failed downloads (not sure what setting it would be on nzbget) but I get this as a result.

![screenshot_2016-01-10-12-30-56](https://cloud.githubusercontent.com/assets/16467698/12223840/156aa91e-b797-11e5-83cb-9f4339887025.png)

Seems to have worked but the next release was never sent to sabnzbd

![screenshot_2016-01-10-12-31-03](https://cloud.githubusercontent.com/assets/16467698/12223844/2ee939be-b797-11e5-815b-927a8deb38c6.png)

Any ideas ??

**Comment by javvydawg** [comment]
Any updates on this ?
